#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum doj5wz_employeetalentprofile_doj5wz_careerpath
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Specialist = 686810000,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Trainee = 686810001,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Manager = 686810002,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Expert = 686810003,
}

[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum doj5wz_employeetalentprofile_doj5wz_executivemanagementlevel
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Employee = 686810000,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	ExecutiveBoard = 686810001,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Management = 686810002,
}

[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum doj5wz_employeetalentprofile_doj5wz_gender
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	male = 686810000,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	female = 686810001,
}

/// <summary>
/// Status of the Employee Talent Profile
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum doj5wz_employeetalentprofile_statecode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Active = 0,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Inactive = 1,
}

/// <summary>
/// Reason for the status of the Employee Talent Profile
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum doj5wz_employeetalentprofile_statuscode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Active = 1,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Inactive = 2,
}

/// <summary>
/// This table contains detailed talent and HR-related information for employees.
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("doj5wz_employeetalentprofile")]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public partial class doj5wz_employeetalentprofile : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
{
	
		/// <summary>
		/// Available fields, a the time of codegen, for the doj5wz_employeetalentprofile entity
		/// </summary>
		public partial class Fields
		{
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string doj5wz_agemetric = "doj5wz_agemetric";
			public const string doj5wz_bamsreference = "doj5wz_bamsreference";
			public const string doj5wz_careerpath = "doj5wz_careerpath";
			public const string doj5wz_country = "doj5wz_country";
			public const string doj5wz_dateofbirth = "doj5wz_dateofbirth";
			public const string doj5wz_developmentpool = "doj5wz_developmentpool";
			public const string doj5wz_employeetalentprofileId = "doj5wz_employeetalentprofileid";
			public const string Id = "doj5wz_employeetalentprofileid";
			public const string doj5wz_executivemanagementlevel = "doj5wz_executivemanagementlevel";
			public const string doj5wz_firstname = "doj5wz_firstname";
			public const string doj5wz_followupmeasures = "doj5wz_followupmeasures";
			public const string doj5wz_functionalarea = "doj5wz_functionalarea";
			public const string doj5wz_gender = "doj5wz_gender";
			public const string doj5wz_globalemployeegroup = "doj5wz_globalemployeegroup";
			public const string doj5wz_globalidentifier = "doj5wz_globalidentifier";
			public const string doj5wz_hrmanagerfirstname = "doj5wz_hrmanagerfirstname";
			public const string doj5wz_hrmanagerlastname = "doj5wz_hrmanagerlastname";
			public const string doj5wz_hrmanagerusername = "doj5wz_hrmanagerusername";
			public const string doj5wz_lastname = "doj5wz_lastname";
			public const string doj5wz_legalentity = "doj5wz_legalentity";
			public const string doj5wz_localidentifier = "doj5wz_localidentifier";
			public const string doj5wz_location = "doj5wz_location";
			public const string doj5wz_nominationcomments = "doj5wz_nominationcomments";
			public const string doj5wz_organizationalunit = "doj5wz_organizationalunit";
			public const string doj5wz_selfnomination = "doj5wz_selfnomination";
			public const string doj5wz_talentpoolend = "doj5wz_talentpoolend";
			public const string doj5wz_talentpoolstart = "doj5wz_talentpoolstart";
			public const string doj5wz_targetmanagerfirstname = "doj5wz_targetmanagerfirstname";
			public const string doj5wz_targetmanagerlastname = "doj5wz_targetmanagerlastname";
			public const string doj5wz_username = "doj5wz_username";
			public const string doj5wz_usersystemid = "doj5wz_usersystemid";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OwnerId = "ownerid";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string statecode = "statecode";
			public const string statuscode = "statuscode";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
		}
	
	/// <summary>
	/// Default Constructor.
	/// </summary>
	public doj5wz_employeetalentprofile() : 
			base(EntityLogicalName)
	{
	}
	
	public const string EntityLogicalName = "doj5wz_employeetalentprofile";
	
	public const string EntityLogicalCollectionName = "doj5wz_employeetalentprofiles";
	
	public const string EntitySetName = "doj5wz_employeetalentprofiles";
	
	public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
	
	public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
	
	private void OnPropertyChanged(string propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void OnPropertyChanging(string propertyName)
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
		}
	}
	
	/// <summary>
	/// Unique identifier of the user who created the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
		}
	}
	
	/// <summary>
	/// Date and time when the record was created.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
	public System.Nullable<System.DateTime> CreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
		}
	}
	
	/// <summary>
	/// Unique identifier of the delegate user who created the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("doj5wz_agemetric")]
	public System.Nullable<int> doj5wz_agemetric
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("doj5wz_agemetric");
		}
		set
		{
			this.OnPropertyChanging("doj5wz_agemetric");
			this.SetAttributeValue("doj5wz_agemetric", value);
			this.OnPropertyChanged("doj5wz_agemetric");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("doj5wz_bamsreference")]
	public System.Nullable<bool> doj5wz_bamsreference
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("doj5wz_bamsreference");
		}
		set
		{
			this.OnPropertyChanging("doj5wz_bamsreference");
			this.SetAttributeValue("doj5wz_bamsreference", value);
			this.OnPropertyChanged("doj5wz_bamsreference");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("doj5wz_careerpath")]
	public virtual doj5wz_employeetalentprofile_doj5wz_careerpath? doj5wz_careerpath
	{
		get
		{
			return ((doj5wz_employeetalentprofile_doj5wz_careerpath?)(EntityOptionSetEnum.GetEnum(this, "doj5wz_careerpath")));
		}
		set
		{
			this.OnPropertyChanging("doj5wz_careerpath");
			this.SetAttributeValue("doj5wz_careerpath", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("doj5wz_careerpath");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("doj5wz_country")]
	public string doj5wz_country
	{
		get
		{
			return this.GetAttributeValue<string>("doj5wz_country");
		}
		set
		{
			this.OnPropertyChanging("doj5wz_country");
			this.SetAttributeValue("doj5wz_country", value);
			this.OnPropertyChanged("doj5wz_country");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("doj5wz_dateofbirth")]
	public string doj5wz_dateofbirth
	{
		get
		{
			return this.GetAttributeValue<string>("doj5wz_dateofbirth");
		}
		set
		{
			this.OnPropertyChanging("doj5wz_dateofbirth");
			this.SetAttributeValue("doj5wz_dateofbirth", value);
			this.OnPropertyChanged("doj5wz_dateofbirth");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("doj5wz_developmentpool")]
	public string doj5wz_developmentpool
	{
		get
		{
			return this.GetAttributeValue<string>("doj5wz_developmentpool");
		}
		set
		{
			this.OnPropertyChanging("doj5wz_developmentpool");
			this.SetAttributeValue("doj5wz_developmentpool", value);
			this.OnPropertyChanged("doj5wz_developmentpool");
		}
	}
	
	/// <summary>
	/// Unique identifier for entity instances
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("doj5wz_employeetalentprofileid")]
	public System.Nullable<System.Guid> doj5wz_employeetalentprofileId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("doj5wz_employeetalentprofileid");
		}
		set
		{
			this.OnPropertyChanging("doj5wz_employeetalentprofileId");
			this.SetAttributeValue("doj5wz_employeetalentprofileid", value);
			if (value.HasValue)
			{
				base.Id = value.Value;
			}
			else
			{
				base.Id = System.Guid.Empty;
			}
			this.OnPropertyChanged("doj5wz_employeetalentprofileId");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("doj5wz_employeetalentprofileid")]
	public override System.Guid Id
	{
		get
		{
			return base.Id;
		}
		set
		{
			this.doj5wz_employeetalentprofileId = value;
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("doj5wz_executivemanagementlevel")]
	public virtual doj5wz_employeetalentprofile_doj5wz_executivemanagementlevel? doj5wz_executivemanagementlevel
	{
		get
		{
			return ((doj5wz_employeetalentprofile_doj5wz_executivemanagementlevel?)(EntityOptionSetEnum.GetEnum(this, "doj5wz_executivemanagementlevel")));
		}
		set
		{
			this.OnPropertyChanging("doj5wz_executivemanagementlevel");
			this.SetAttributeValue("doj5wz_executivemanagementlevel", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("doj5wz_executivemanagementlevel");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("doj5wz_firstname")]
	public string doj5wz_firstname
	{
		get
		{
			return this.GetAttributeValue<string>("doj5wz_firstname");
		}
		set
		{
			this.OnPropertyChanging("doj5wz_firstname");
			this.SetAttributeValue("doj5wz_firstname", value);
			this.OnPropertyChanged("doj5wz_firstname");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("doj5wz_followupmeasures")]
	public System.Nullable<bool> doj5wz_followupmeasures
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("doj5wz_followupmeasures");
		}
		set
		{
			this.OnPropertyChanging("doj5wz_followupmeasures");
			this.SetAttributeValue("doj5wz_followupmeasures", value);
			this.OnPropertyChanged("doj5wz_followupmeasures");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("doj5wz_functionalarea")]
	public string doj5wz_functionalarea
	{
		get
		{
			return this.GetAttributeValue<string>("doj5wz_functionalarea");
		}
		set
		{
			this.OnPropertyChanging("doj5wz_functionalarea");
			this.SetAttributeValue("doj5wz_functionalarea", value);
			this.OnPropertyChanged("doj5wz_functionalarea");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("doj5wz_gender")]
	public virtual doj5wz_employeetalentprofile_doj5wz_gender? doj5wz_gender
	{
		get
		{
			return ((doj5wz_employeetalentprofile_doj5wz_gender?)(EntityOptionSetEnum.GetEnum(this, "doj5wz_gender")));
		}
		set
		{
			this.OnPropertyChanging("doj5wz_gender");
			this.SetAttributeValue("doj5wz_gender", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("doj5wz_gender");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("doj5wz_globalemployeegroup")]
	public string doj5wz_globalemployeegroup
	{
		get
		{
			return this.GetAttributeValue<string>("doj5wz_globalemployeegroup");
		}
		set
		{
			this.OnPropertyChanging("doj5wz_globalemployeegroup");
			this.SetAttributeValue("doj5wz_globalemployeegroup", value);
			this.OnPropertyChanged("doj5wz_globalemployeegroup");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("doj5wz_globalidentifier")]
	public string doj5wz_globalidentifier
	{
		get
		{
			return this.GetAttributeValue<string>("doj5wz_globalidentifier");
		}
		set
		{
			this.OnPropertyChanging("doj5wz_globalidentifier");
			this.SetAttributeValue("doj5wz_globalidentifier", value);
			this.OnPropertyChanged("doj5wz_globalidentifier");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("doj5wz_hrmanagerfirstname")]
	public string doj5wz_hrmanagerfirstname
	{
		get
		{
			return this.GetAttributeValue<string>("doj5wz_hrmanagerfirstname");
		}
		set
		{
			this.OnPropertyChanging("doj5wz_hrmanagerfirstname");
			this.SetAttributeValue("doj5wz_hrmanagerfirstname", value);
			this.OnPropertyChanged("doj5wz_hrmanagerfirstname");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("doj5wz_hrmanagerlastname")]
	public string doj5wz_hrmanagerlastname
	{
		get
		{
			return this.GetAttributeValue<string>("doj5wz_hrmanagerlastname");
		}
		set
		{
			this.OnPropertyChanging("doj5wz_hrmanagerlastname");
			this.SetAttributeValue("doj5wz_hrmanagerlastname", value);
			this.OnPropertyChanged("doj5wz_hrmanagerlastname");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("doj5wz_hrmanagerusername")]
	public string doj5wz_hrmanagerusername
	{
		get
		{
			return this.GetAttributeValue<string>("doj5wz_hrmanagerusername");
		}
		set
		{
			this.OnPropertyChanging("doj5wz_hrmanagerusername");
			this.SetAttributeValue("doj5wz_hrmanagerusername", value);
			this.OnPropertyChanged("doj5wz_hrmanagerusername");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("doj5wz_lastname")]
	public string doj5wz_lastname
	{
		get
		{
			return this.GetAttributeValue<string>("doj5wz_lastname");
		}
		set
		{
			this.OnPropertyChanging("doj5wz_lastname");
			this.SetAttributeValue("doj5wz_lastname", value);
			this.OnPropertyChanged("doj5wz_lastname");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("doj5wz_legalentity")]
	public string doj5wz_legalentity
	{
		get
		{
			return this.GetAttributeValue<string>("doj5wz_legalentity");
		}
		set
		{
			this.OnPropertyChanging("doj5wz_legalentity");
			this.SetAttributeValue("doj5wz_legalentity", value);
			this.OnPropertyChanged("doj5wz_legalentity");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("doj5wz_localidentifier")]
	public string doj5wz_localidentifier
	{
		get
		{
			return this.GetAttributeValue<string>("doj5wz_localidentifier");
		}
		set
		{
			this.OnPropertyChanging("doj5wz_localidentifier");
			this.SetAttributeValue("doj5wz_localidentifier", value);
			this.OnPropertyChanged("doj5wz_localidentifier");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("doj5wz_location")]
	public string doj5wz_location
	{
		get
		{
			return this.GetAttributeValue<string>("doj5wz_location");
		}
		set
		{
			this.OnPropertyChanging("doj5wz_location");
			this.SetAttributeValue("doj5wz_location", value);
			this.OnPropertyChanged("doj5wz_location");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("doj5wz_nominationcomments")]
	public string doj5wz_nominationcomments
	{
		get
		{
			return this.GetAttributeValue<string>("doj5wz_nominationcomments");
		}
		set
		{
			this.OnPropertyChanging("doj5wz_nominationcomments");
			this.SetAttributeValue("doj5wz_nominationcomments", value);
			this.OnPropertyChanged("doj5wz_nominationcomments");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("doj5wz_organizationalunit")]
	public string doj5wz_organizationalunit
	{
		get
		{
			return this.GetAttributeValue<string>("doj5wz_organizationalunit");
		}
		set
		{
			this.OnPropertyChanging("doj5wz_organizationalunit");
			this.SetAttributeValue("doj5wz_organizationalunit", value);
			this.OnPropertyChanged("doj5wz_organizationalunit");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("doj5wz_selfnomination")]
	public System.Nullable<bool> doj5wz_selfnomination
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("doj5wz_selfnomination");
		}
		set
		{
			this.OnPropertyChanging("doj5wz_selfnomination");
			this.SetAttributeValue("doj5wz_selfnomination", value);
			this.OnPropertyChanged("doj5wz_selfnomination");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("doj5wz_talentpoolend")]
	public string doj5wz_talentpoolend
	{
		get
		{
			return this.GetAttributeValue<string>("doj5wz_talentpoolend");
		}
		set
		{
			this.OnPropertyChanging("doj5wz_talentpoolend");
			this.SetAttributeValue("doj5wz_talentpoolend", value);
			this.OnPropertyChanged("doj5wz_talentpoolend");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("doj5wz_talentpoolstart")]
	public string doj5wz_talentpoolstart
	{
		get
		{
			return this.GetAttributeValue<string>("doj5wz_talentpoolstart");
		}
		set
		{
			this.OnPropertyChanging("doj5wz_talentpoolstart");
			this.SetAttributeValue("doj5wz_talentpoolstart", value);
			this.OnPropertyChanged("doj5wz_talentpoolstart");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("doj5wz_targetmanagerfirstname")]
	public string doj5wz_targetmanagerfirstname
	{
		get
		{
			return this.GetAttributeValue<string>("doj5wz_targetmanagerfirstname");
		}
		set
		{
			this.OnPropertyChanging("doj5wz_targetmanagerfirstname");
			this.SetAttributeValue("doj5wz_targetmanagerfirstname", value);
			this.OnPropertyChanged("doj5wz_targetmanagerfirstname");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("doj5wz_targetmanagerlastname")]
	public string doj5wz_targetmanagerlastname
	{
		get
		{
			return this.GetAttributeValue<string>("doj5wz_targetmanagerlastname");
		}
		set
		{
			this.OnPropertyChanging("doj5wz_targetmanagerlastname");
			this.SetAttributeValue("doj5wz_targetmanagerlastname", value);
			this.OnPropertyChanged("doj5wz_targetmanagerlastname");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("doj5wz_username")]
	public string doj5wz_username
	{
		get
		{
			return this.GetAttributeValue<string>("doj5wz_username");
		}
		set
		{
			this.OnPropertyChanging("doj5wz_username");
			this.SetAttributeValue("doj5wz_username", value);
			this.OnPropertyChanged("doj5wz_username");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("doj5wz_usersystemid")]
	public string doj5wz_usersystemid
	{
		get
		{
			return this.GetAttributeValue<string>("doj5wz_usersystemid");
		}
		set
		{
			this.OnPropertyChanging("doj5wz_usersystemid");
			this.SetAttributeValue("doj5wz_usersystemid", value);
			this.OnPropertyChanged("doj5wz_usersystemid");
		}
	}
	
	/// <summary>
	/// Sequence number of the import that created this record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
	public System.Nullable<int> ImportSequenceNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
		}
		set
		{
			this.OnPropertyChanging("ImportSequenceNumber");
			this.SetAttributeValue("importsequencenumber", value);
			this.OnPropertyChanged("ImportSequenceNumber");
		}
	}
	
	/// <summary>
	/// Unique identifier of the user who modified the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
		}
	}
	
	/// <summary>
	/// Date and time when the record was modified.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
	public System.Nullable<System.DateTime> ModifiedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
		}
	}
	
	/// <summary>
	/// Unique identifier of the delegate user who modified the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
		}
	}
	
	/// <summary>
	/// Date and time that the record was migrated.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
	public System.Nullable<System.DateTime> OverriddenCreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
		}
		set
		{
			this.OnPropertyChanging("OverriddenCreatedOn");
			this.SetAttributeValue("overriddencreatedon", value);
			this.OnPropertyChanged("OverriddenCreatedOn");
		}
	}
	
	/// <summary>
	/// Owner Id
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
	public Microsoft.Xrm.Sdk.EntityReference OwnerId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
		}
		set
		{
			this.OnPropertyChanging("OwnerId");
			this.SetAttributeValue("ownerid", value);
			this.OnPropertyChanged("OwnerId");
		}
	}
	
	/// <summary>
	/// Unique identifier for the business unit that owns the record
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
	public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
		}
	}
	
	/// <summary>
	/// Unique identifier for the team that owns the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
	public Microsoft.Xrm.Sdk.EntityReference OwningTeam
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
		}
	}
	
	/// <summary>
	/// Unique identifier for the user that owns the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
	public Microsoft.Xrm.Sdk.EntityReference OwningUser
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
		}
	}
	
	/// <summary>
	/// Status of the Employee Talent Profile
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
	public virtual doj5wz_employeetalentprofile_statecode? statecode
	{
		get
		{
			return ((doj5wz_employeetalentprofile_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
		}
		set
		{
			this.OnPropertyChanging("statecode");
			this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("statecode");
		}
	}
	
	/// <summary>
	/// Reason for the status of the Employee Talent Profile
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
	public virtual doj5wz_employeetalentprofile_statuscode? statuscode
	{
		get
		{
			return ((doj5wz_employeetalentprofile_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
		}
		set
		{
			this.OnPropertyChanging("statuscode");
			this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("statuscode");
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
	public System.Nullable<int> TimeZoneRuleVersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
		}
		set
		{
			this.OnPropertyChanging("TimeZoneRuleVersionNumber");
			this.SetAttributeValue("timezoneruleversionnumber", value);
			this.OnPropertyChanged("TimeZoneRuleVersionNumber");
		}
	}
	
	/// <summary>
	/// Time zone code that was in use when the record was created.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
	public System.Nullable<int> UTCConversionTimeZoneCode
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
		}
		set
		{
			this.OnPropertyChanging("UTCConversionTimeZoneCode");
			this.SetAttributeValue("utcconversiontimezonecode", value);
			this.OnPropertyChanged("UTCConversionTimeZoneCode");
		}
	}
	
	/// <summary>
	/// Version Number
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
	public System.Nullable<long> VersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
		}
	}
}
#pragma warning restore CS1591
